# Generated by Django 4.2.6 on 2024-07-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product_sid_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sid',
            new_name='seller_id',
        ),
    ]
